# Generated by Django 5.2 on 2025-07-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmodel",
            name="updated_at",
        ),
    ]
