# Generated by Django 5.2 on 2025-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_chatmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reasoning_content",
            field=models.TextField(blank=True, null=True, verbose_name="推理内容"),
        ),
    ]
