# Generated by Django 5.2 on 2025-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_reasoning_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message_resp_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="消息的响应ID"
            ),
        ),
    ]
