# Generated by Django 5.2 on 2025-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatmessage_message_resp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmodel",
            name="ep_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="推理接入点ID",
            ),
        ),
    ]
