# Generated by Django 5.2 on 2025-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatmodel_ep_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="show_thinking",
            field=models.BooleanField(default=False, verbose_name="是否显示推理"),
        ),
    ]
