# Generated by Django 5.2 on 2025-08-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatmessage_show_thinking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="show_thinking",
        ),
    ]
