# Generated by Django 5.2 on 2025-07-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial_migration"),
    ]

    operations = []
