# Generated by Django 5.2 on 2025-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20250728_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "保密"), (1, "男"), (2, "女")],
                default=1,
                verbose_name="性别",
            ),
        ),
    ]
