# Generated by Django 5.2 on 2025-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "保密"), (1, "男"), (2, "女")],
                default=0,
                verbose_name="性别",
            ),
        ),
    ]
