# Generated by Django 5.2 on 2025-08-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile",
        ),
    ]
