# Generated by Django 5.2 on 2025-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "该邮箱已被使用"},
                max_length=254,
                unique=True,
                verbose_name="邮箱",
            ),
        ),
    ]
