# Generated by Django 5.2 on 2025-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="uploads/avatar/default.png",
                upload_to="uploads/avatar",
                verbose_name="头像",
            ),
        ),
    ]
