# Generated by Django 5.2 on 2025-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar/default.png", upload_to="avatar", verbose_name="头像"
            ),
        ),
    ]
