# Generated by Django 5.2 on 2025-08-05 16:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="默认用户", max_length=128, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar/default.png",
                upload_to=users.models.user_avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]
