# Generated by Django 5.2 on 2025-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_name_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=128, verbose_name="昵称"),
        ),
    ]
